### ISSUE TITLE
`nupack_complex_base_pair_probability_constraint` falsely flags a noncompetitive domain as competitive if it appears in multiple strands

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/dsd#144]
## Expected Behavior
No errors

## Current Behavior
AssertionError caused by 
https://github.com/UC-Davis-molecular-computing/dsd/blob/344b9989145d280ce8853e2b5a8a0936b5deeb09/dsd/constraints.py#L5655

## Reproducible Example

```py
import dsd.constraints as dc
import dsd.search as ds  # type: ignore

one: dc.Strand = dc.Strand(['x', 'z'])
two: dc.Strand = dc.Strand(['x*', 'z'])

# Set domain pools
dummy = dc.DomainPool('dummy', 5)
for s in [one, two]:
  for d in s.domains:
    d.pool = dummy

dc.nupack_complex_base_pair_probability_constraint([dc.Complex((one, two))])
```

This design contains two instances of the z domain, but since there is no z*, they are noncompetitive and thus, should not flag an error.

## Possible Solution

We can remove this assertion. Input validation for competition is already done here:

https://github.com/UC-Davis-molecular-computing/dsd/blob/dev/dsd/constraints.py#L5847-L5855

So at this point, there is no need to make this assertion, and this assertion does not actually need to be true for the rest of the code logic in this function to run. Any unpaired domains added to the `implicit_seen_domains` will be ignored anyways.

**Comment by dave-doty** [comment]
> We can remove this assertion.

Sounds good, can you make a PR with that change?
