### ISSUE TITLE
allow to specify multi-stranded Complexes, and add a ComplexConstraint type

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/dsd#19]
Currently, dsd only allows one to specify Strands and Domains. Although complementary Domains between Strands implies that at some point one expects them to be bound, there's no way to directly specify which multi-stranded complexes are expected.

Allow the Design to specify such complexes, as well as a new type of constraint, `ComplexConstraint`. One example of a constraint would be to specify a desired secondary structure of the complex (using [dot-bracket notation](https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/rna_structure_notations.html)) and ask NUPACK to verify that its minimum free energy structure is that, or to specify that certain base-pair probabilities in the complex are above/below a certain threshold.

One could also imagine a common case where if each Domain has no complement on another strand, or exactly one, you infer from that the intended secondary structure and verify it's that with high probability (via base-pairing probabilities).

**Comment by dave-doty** [comment]
Maybe also `DomainSetConstraint` (or `DomainTupleConstraint` if we care about order).

**Comment by dave-doty** [comment]
Good constraint to specify: user gives strands for complex. Some of them have complementary domains, but no "competition", i.e., if some strand has an `a`, then at most one `a*` appears on any strand in the complex. Then without specifying any other information, the code should infer that the user wants complementary domains to be bound. It should not be binary and check the MFE, because even very strongly bound domains could have an A/T pair at the end, which may well be unpaired in the MFE.

One example could be that we check the base-pair probabilities returned by NUPACK, ensure that they are > 99% for base pairs in the middle of a domain, > 40% for base pairs on the end of a domain (due to breathing), and < 1% for base pairs that are not between two complementary domains.

TODO: Play with NUPACK to see what reasonable base-pair probabilities are for certain complexes, to come up with reasonable defaults.

**Comment by dave-doty** [comment]
Papers to use for example systems to stress-test library:

https://www.dna.caltech.edu/DNAresearch_publications.html#SeesawDigitalCircuits (seesaw circuits)

https://www.dna.caltech.edu/DNAresearch_publications.html#DynamicDNA (two-domain DSD implementation of CRNs)

**Comment by UnHumbleBen** [comment]
@dave-doty I'm a bit confused about the evaluation algorithm we discussed last week

Let's suppose the user inputs complex:
```
strand1 = a-b-c-d
strand2 = a*-b*-c*-d*
strand3 = e-f-g-h

complexA = [strand1, strand2, strand3]
```

Based on what we discussed in meeting last week, I think you said we can **ignore the boundaries** between the strands and just focus on the domains that make it up? Did you mean that we should combine the strands into a **single** long strand?

```
strand_eq = a-b-c-d-a*-b*-c*-d*-e-f-g-h
complexB = [strand_eq]
```

Did I misinterpret what you meant? I think it makes more sense to keep the strands separate as in `complexA`.


Then we pass it into [Nupack's `complex_analysis` function](https://piercelab-caltech.github.io/nupack-docs/analysis/#run-a-complex-analysis-job) and analyze base pair probabilities between domains.

**Comment by dave-doty** [comment]
> **EDIT**: After working on it some more, I think I misinterpreted what you said. By "ignore the boundaries", you were actually referring to when we concatenate all the strand domain/sequences together in order to compute which indices to query to find the base pairs between two domains from the returned numpy array of `complex_analysis`.

Correct. We will call NUPACK with the strands separated. It's just a way to map indices into each strand/domain to indices as returned by NUPACK, which uses a single indexing for multiple strands.
