### ISSUE TITLE
update README with instructions on installing NUPACK 4

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/dsd#26]
It's fine to just link to the instructions for installing NUPACK 4, but essentially it should mention that in order to call [`pfunc4`](https://github.com/UC-Davis-molecular-computing/dsd/blob/master/dsd/vienna_nupack.py#L101) and related functions, NUPACK 4 must be installed, and it should give similar instructions as in the current README for how to quickly test whether it is installed correctly..

BTW, we still need to add versions of functions such as [`secondary_structure_single_strand`](https://github.com/UC-Davis-molecular-computing/dsd/blob/master/dsd/vienna_nupack.py#L428), and functions such as [`nupack_strand_secondary_structure_constraint`](https://github.com/UC-Davis-molecular-computing/dsd/blob/master/dsd/constraints.py#L2781)) for creating constraints that call these NUPACK 4 functions. (Maybe this should be its own "enhancement" issue, but I'm mentioned it here for now.)

**Comment by UnHumbleBen** [comment]
Do we want a NUPACK 4 version of every function that uses `pfunc` and every function that calls a `pfunc` calling function? For example, `domain_no_sec_struct` calls `secondary_structure_single_strand`, which calls `pfunc`, so we should have a `domain_no_sec_struct4` function?

**Comment by dave-doty** [comment]
> Do we want a NUPACK 4 version of every function that uses `pfunc` and every function that calls a `pfunc` calling function? For example, `domain_no_sec_struct` calls `secondary_structure_single_strand`, which calls `pfunc`, so we should have a `domain_no_sec_struct4` function?

What do you think? I recall when we discussed this that we thought about making the call to NUPACK 4 just an optional argument to the original `pfunc`, but that it made sense to write a new function since it would have a different parameter list. If that parameter list makes sense for the other functions as well, then it makes sense to make them separately defined functions.
